[package]
name = "trace_me"
version = "0.1.0"
authors = ["Tim de Jager"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
